import Link from "next/link";
import { SiteShell } from "../components/SiteShell";
import { Brandmark } from "../components/BrandLogo";
import { FinalCTA, PageHero } from "../components/PageBlocks";
import { createPageMetadata } from "../lib/metadata";
export const metadata = createPageMetadata({ title: "About Our Maine Marketing Studio", description: "Meet Green Falls Co., a Maine marketing studio with hands-on Klaviyo, HubSpot and Customer.io experience. Websites, email and practical help for small businesses.", path: "/about" });
export default function AboutPage(){return <SiteShell><main id="main-content">
<PageHero title="About Green Falls Co." intro="We’re a Maine marketing studio for independent businesses across the Northeast. We build websites, create customer emails and help owners make practical use of AI."/>
<section className="section section-tone-dark"><div className="shell about-origin"><div className="origin-mark"><Brandmark className="origin-brandmark" inverse/></div><div><h2>Experience building and running email programs.</h2><p>The experience behind Green Falls includes building an agency’s customer email service and running email programs for several brands. That work spans welcome emails, ways to reconnect with past customers, choosing who gets each message, and reviewing results.</p><p>We’ve worked hands-on in Klaviyo, HubSpot and Customer.io. We bring that view of the customer relationship to website projects too: what should happen after someone makes an inquiry, signs up or buys?</p><Link className="text-link" href="/services/email-lifecycle-retention">Explore email marketing</Link></div></div></section>
<section className="section"><div className="shell detail-two-col"><h2>We think beyond the first inquiry.</h2><div><p>Getting someone’s attention is only part of the work. They also need answers before they buy, a reply when they ask a question and a reason to come back. We plan websites and customer emails around those moments.</p><p>We agree on what you’ll receive before starting, review the work with you and hand over the files, access and instructions you’ll need to keep using it.</p><Link className="text-link" href="/approach">How a project works</Link></div></div></section>
<section className="section shell northeast-section"><div className="detail-two-col"><h2>Why Green Falls?</h2><div><p>The name comes from Green Falls in Baxter State Park. The waterfall on our homepage is the original photograph that inspired the identity.</p><p>Our focus is independent businesses: trades, restaurants, shops, repair businesses and specialists. Projects can include in-person meetings in Maine or be handled remotely.</p></div></div></section>
<FinalCTA title="Have a project in mind?" body="Tell us what you want to make, change or get working. We’ll let you know how we can help."/>
</main></SiteShell>}
