import { SiteShell } from "../components/SiteShell";
import { FinalCTA, PageHero } from "../components/PageBlocks";
import { createPageMetadata } from "../lib/metadata";
export const metadata=createPageMetadata({title:"Our Website & Marketing Project Process",description:"See how a Green Falls project works: agree on scope and cost, review drafts, test the result and receive the files, access and instructions you need.",path:"/approach"});
const steps=[
["Discuss the project","Tell us what prompted the project, what you already have and any deadlines or budget limits. We’ll ask about your customers and who will use or maintain the finished work.","You share: the goal, existing website or tools, and any fixed requirements."],
["Agree on the work and cost","We write down what we’ll make, who does what, when you’ll review it and what it costs. You can see what’s included and what would need a separate decision before work starts.","You receive: a written project plan to review before committing."],
["Review the work as it develops","We share the page, email or workflow in context so you can judge the wording, design and behavior together. Questions and changes are recorded against the agreed plan.","You review: actual drafts and working previews, with specific decisions called out."],
["Test and hand over","We check the agreed customer actions, give you the relevant files and access, and explain how to update the work. If ongoing support is included, we agree on the reporting and review schedule.","You receive: the finished work, ownership details and maintenance instructions."]];
export default function ApproachPage(){return <SiteShell><main id="main-content"><PageHero title="What happens when you hire us." intro="You’ll review the project plan before we start and the work before it launches. Here’s what to expect along the way."/>
<section className="section section-tone-dark"><div className="shell"><ol className="project-steps">{steps.map(([title,body,note],i)=><li key={title}><span>{i+1}</span><div><h2>{title}</h2><p>{body}</p><p className="step-output"><strong>{note.slice(0, note.indexOf(":"))}</strong><span>{note.slice(note.indexOf(":") + 1).trim()}</span></p></div></li>)}</ol></div></section>
<section className="section"><div className="shell detail-two-col"><h2>What we’ll need from you.</h2><div><p>A person who can make project decisions, access to the relevant systems and time to review the work. We’ll identify the required copy, photos, product details or business information before the work begins.</p><p>If a requirement changes, we’ll discuss its effect on the work and cost before proceeding. You’ll know who is responsible for each action.</p></div></div></section>
<FinalCTA title="Tell us what you’re planning." body="Share the project, any timing you’re working toward and what you already have."/></main></SiteShell>}
