import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "../../components/SiteShell";
import { FAQ, PageHero } from "../../components/PageBlocks";
import { StructuredData } from "../../components/StructuredData";
import { ServiceDiagram } from "../../components/ServiceDiagram";
import { StudioEmail } from "../../components/StudioEmail";
import { ContactForm, type HelpArea } from "../../contact/ContactForm";
import { services, type Service } from "../../lib/content";
import { createPageMetadata, serviceSchema } from "../../lib/metadata";
export function generateStaticParams(){return services.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const service=services.find(s=>s.slug===slug);return service?createPageMetadata({title:service.seoTitle,description:service.description,path:`/services/${service.slug}`}):{}}
const specifics: Record<Service["artifact"], { heading: string; body: string; cta: string; note: string; area: HelpArea }> = {
 website:{heading:"Start with the pages customers need.",body:"We plan pages around your services, location and the questions customers ask. We also agree on who will update the site and what it needs to connect to, such as a booking tool.",cta:"Tell us about your website.",note:"Share your current site, if you have one, and what the new or improved site needs to do.",area:"Website and search"},
 email:{heading:"Decide who gets each message and why.",body:"We look at how people join your list and what happens when they buy or visit. Then we plan the messages, who should get them, when they send and who answers replies.",cta:"Tell us about your customer emails.",note:"Share your email platform, what you send today and the part you want help with.",area:"Email marketing"},
 ai:{heading:"Test one task before expanding it.",body:"Choose a task you repeat, such as preparing an answer or sorting incoming requests. We gather the information it needs, set up a person to check the result and test what happens when information is missing or the request is unusual.",cta:"Which task keeps coming back?",note:"Describe the task, where its information lives and who checks the result today.",area:"Practical AI"},
 plan:{heading:"A plan that says what to do and who will do it.",body:"We work within your budget, your team’s time and the commitments you already have. Each recommendation explains why it matters, who will do it, what needs to happen first and how you’ll know if it helped.",cta:"What marketing decision are you weighing?",note:"Tell us what you’re considering, any proposals you have and the limits on budget or timing.",area:"Marketing consultation"}
};
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=services.find(s=>s.slug===slug);if(!service)notFound();const spec=specifics[service.artifact];const shortName=service.short.toLowerCase().replace(/\bai\b/g, "AI");return <SiteShell><main id="main-content" className={`service-specific service-${service.artifact}`}><StructuredData data={serviceSchema(service)}/><PageHero backHref="/services" backLabel="All services" title={service.title} intro={service.intro}><a className="button" href="#contact">Discuss a project</a></PageHero>
<section className="section shell service-scope"><div className="scope-deliverables"><h2>What your project can include</h2><ul className="plain-list">{service.includes.map(s=><li key={s}>{s}</li>)}</ul><p>We’ll agree on the work, cost and timing in your proposal before starting.</p></div><div className="scope-context"><h2>{spec.heading}</h2><p>{spec.body}</p><h3>When this service helps</h3><ul className="plain-list">{service.symptoms.map(s=><li key={s}>{s}</li>)}</ul></div></section>
<ServiceDiagram artifact={service.artifact}/>
{service.artifact==="email"&&<section className="section"><div className="shell detail-two-col"><h2>We check who gets each email and when.</h2><div><p>We check the recipient list, links, phone layout and where replies go. For emails that send automatically, we set the event that starts them and the conditions that stop them. For example, a booked appointment should stop further booking reminders.</p><p>We check whether emails arrive and whether people reply, buy or book. Clicks and unsubscribes help us decide what to change.</p></div></div></section>}
{service.artifact==="website"&&<section className="section"><div className="shell detail-two-col"><h2>Test the actions that matter.</h2><div><p>We check menus, reading on a phone, required form fields and whether inquiries arrive. We also check that search engines can reach your pages and read accurate titles, descriptions and business details.</p><p>You receive access to the site and instructions for routine updates. We choose the website system with you before building.</p></div></div></section>}
{service.details.map(detail=><section className="section" key={detail.heading}><div className="shell detail-two-col"><h2>{detail.heading}</h2><div>{detail.paragraphs.map(p=><p key={p}>{p}</p>)}</div></div></section>)}
{service.artifact==="email"&&<section className="section example-section" aria-labelledby="email-sample-heading"><div className="shell email-showcase email-service-example"><div className="email-showcase-intro"><h2 id="email-sample-heading">What a customer email can look like.</h2><p>A sample newsletter we designed to show the layout, tone and single next step we aim for.</p><p>It’s a design example rendered on this page, not a sent campaign.</p></div><StudioEmail/></div></section>}
<section className="section"><div className="shell detail-two-col"><h2>Questions about {shortName}</h2><FAQ items={service.faqs}/></div></section>
<section className="section"><div className="shell detail-two-col"><h2>Read before you decide</h2><ul className="plain-list">{service.related.map(link=><li key={link.href}><Link className="text-link" href={link.href}>{link.label}</Link></li>)}</ul></div></section>
<section id="contact" className="home-contact" aria-labelledby="service-contact-heading"><div className="shell home-contact-grid"><div className="home-contact-copy"><h2 id="service-contact-heading">{spec.cta}</h2><p>{spec.note}</p><p>We’ll reply by email with any questions and let you know how we can help.</p><p className="home-contact-email">Prefer email? <a href="mailto:info@greenfalls.co">info@greenfalls.co</a></p></div><ContactForm source={`service-${service.artifact}`} defaultArea={spec.area}/></div></section></main></SiteShell>}
