import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "../../components/SiteShell";
import { PageHero, FAQ } from "../../components/PageBlocks";
import { ContactForm } from "../../contact/ContactForm";
import { createPageMetadata } from "../../lib/metadata";
const audiences = {
 contractors: {
 seoTitle: "Contractor Website Design & Local SEO in Maine", description: "Website design and local SEO for Maine contractors. Explain your services and coverage, simplify estimate requests and make sure inquiries reach your team.",
 title: "Website design for Maine contractors", intro: "Help homeowners understand the work you take on, where you work and how to request an estimate. We review and improve contractor websites, local search information and the steps that follow an inquiry.",
 sections: [
 ["Make it clear which jobs you take on.","Roof repair and roof replacement need different explanations. So do a small deck repair and a new build. We organize pages around the services you actually offer, explain the jobs that fit and make your service area easy to find."],
 ["Ask for enough detail to start a conversation.","A useful estimate form can begin with a name, contact details, town and a short description. We agree on what your team needs before adding more questions. We check the form on a phone, confirm that it reaches the right inbox and explain what happens next."],
 ["Keep the website and local listing consistent.","We review business details, service descriptions and the links from your Google Business Profile. Your coverage should reflect where you genuinely work. We don’t promise a particular ranking or add towns you don’t serve."],
 ["Know who’s handling each inquiry.","We can help define who replies, what information is needed and when a reminder would be useful. Any automated follow-up should stop when it’s no longer relevant. Tracking setup helps distinguish a website inquiry from a confirmed job."]
 ],
 start: "Start with a website review and an agreed list of fixes. We’ll check your most important service pages, the mobile experience and inquiry delivery, then quote the work that needs attention. A rebuild is a separate decision.",
 service: "/services/website-creation-seo-aeo", serviceLabel: "Read about website design and search", guide: "/insights/follow-up-after-quote-request", guideLabel: "Plan what happens after a quote request",
 faqs: [{q:"Can you work on the site we already have?",a:"We’ll review the platform and access first. If targeted fixes are practical, we can scope those. If the current setup prevents the changes you need, we’ll explain the options before recommending a rebuild."},{q:"Do we need to buy advertising?",a:"No. Website improvements and advertising are separate decisions. We start by making sure customers can understand your services and that inquiries reach your team."},{q:"What should we send you?",a:"Your website address, the services and towns you want inquiries for, and a description of what isn’t working. Please leave customer information and passwords out of the first message."}]
 },
 retailers: {
 seoTitle: "Email Marketing for Independent Retailers", description: "Email campaigns and automation for independent retailers. Welcome subscribers, follow up after purchases and keep customers informed about your shop.",
 title: "Email marketing for independent retailers", intro: "Keep customers informed about the products, services and events they care about. We plan, write, design and build emails for independent shops and ecommerce businesses across Maine and the Northeast.",
 sections: [
 ["Give new subscribers a useful welcome.","A welcome sequence can explain what your shop offers, help someone choose a product or introduce repairs, classes and other services. We decide what a new subscriber needs to know before deciding how many messages to send."],
 ["Follow up when there’s something useful to say.","Care instructions, a relevant accessory or a reminder about a regularly replaced product can make sense after a purchase. Timing depends on what you sell. We check the purchase data and conditions that stop a message before turning on an automated sequence."],
 ["Make campaigns easier to keep up with.","We can plan and produce regular emails for new arrivals, seasonal needs and events. We agree on the schedule, who supplies product information and who approves each message. We don’t assume every email needs a discount."],
 ["Build in the platform you use.","Our background includes hands-on work in Klaviyo, HubSpot and Customer.io. We review your existing setup before recommending another tool. We check subscriber permissions, links, mobile layouts and which people qualify for each send."]
 ],
 start: "Start with one welcome or post-purchase sequence. We’ll agree on the audience, number of messages, writing, design, setup and testing. Ongoing campaigns, platform fees and additional integrations are scoped separately.",
 service: "/services/email-lifecycle-retention", serviceLabel: "Read about our email services", guide: "/insights/email-automations-small-business", guideLabel: "Choose your first email automation",
 faqs: [{q:"Does this work for a shop without an online store?",a:"It can. Classes, repairs, events and new stock may give customers reasons to hear from you. We’ll work with the information you can reliably collect rather than assuming you have online purchase data."},{q:"Can you take over our regular campaigns?",a:"Yes. We can agree on an ongoing schedule after reviewing your list, platform and available content. Campaign production is separate from the first automated sequence unless your proposal includes both."},{q:"How will we know whether it helps?",a:"We choose measures that fit the goal, such as replies, bookings or purchases. Revenue reporting depends on the store and email platform being connected properly. We explain those limits before relying on the numbers."}]
 }
};
export function generateStaticParams(){return Object.keys(audiences).map(audience=>({audience}));}
async function getAudience(params:Promise<{audience:string}>){const {audience}=await params;const item=audiences[audience as keyof typeof audiences];if(!item)notFound();return {item,audience};}
export async function generateMetadata({params}:{params:Promise<{audience:string}>}){const {item,audience}=await getAudience(params);return createPageMetadata({title:item.seoTitle,description:item.description,path:`/who-we-help/${audience}`});}
export default async function AudiencePage({params}:{params:Promise<{audience:string}>}){const {item}=await getAudience(params);return <SiteShell><main id="main-content"><PageHero title={item.title} intro={item.intro} backHref="/who-we-help" backLabel="Who we help"><a className="button" href="#contact">Tell us what you need</a></PageHero><section className="section shell industry-stack">{item.sections.map(([title,body])=><article className="industry-row" key={title}><h2>{title}</h2><p>{body}</p></article>)}</section><section className="section section-tone-blue"><div className="shell detail-two-col"><h2>A manageable first project.</h2><div><p>{item.start}</p><p><Link className="text-link" href={item.service}>{item.serviceLabel}</Link></p><p><Link className="text-link" href={item.guide}>{item.guideLabel}</Link></p></div></div></section><section className="section shell narrow-section"><h2>Before we start</h2><FAQ items={item.faqs}/></section><section id="contact" className="home-contact"><div className="shell home-contact-grid"><div><h2>Tell us where you need help.</h2><p>Share your website, what you offer and what you’d like to improve. We’ll reply with any questions and let you know how we can help.</p></div><ContactForm source="audience" /></div></section></main></SiteShell>}
